version: '3'

services:

  proxy:
    image: nginx
    ports: 
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  baku:
    image: nginx
    volumes:
      - ./baku.html:/usr/share/nginx/html/index.html
